[book]
title = "Go语言定制指南"
authors = ["柴树杉", "史斌", "丁尔男"]
description = "从Go语法书开始定制自己的语言"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "book"

[output.html]
additional-css = ["style.css"]
additional-js = ["custom.js", "bigPicture.js"]
git-repository-url = "https://github.com/chai2010/go-ast-book"
edit-url-template = "https://github.com/chai2010/go-ast-book/edit/master/{path}"
git-repository-icon = "fa-github"
